name = "onix-restaurant"
main = "worker/src/index.ts"
compatibility_date = "2026-09-01"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "onix-db"
database_id = "863beff2-87a0-4c46-8caf-bd26d0b21d3a"
migrations_dir = "migrations"

[triggers]
crons = ["17 * * * *"]

[vars]
DEMO_TTL_HOURS = "24"
