import { Link } from 'react-router-dom';
import { PageShell } from '../components/layout/PageShell';
import { PageHero } from '../components/layout/PageHero';
import { PrivateDiningExperience } from '../components/ui/PrivateDiningExperience';
import { effectiveContent } from '../lib/dataSource';

export function VisitPage(){
  const c=effectiveContent();
  return <PageShell>
    <PageHero eyebrow={c.pages.visit.heroEyebrow} title={c.pages.visit.heroTitle} className="visit">{c.pages.visit.heroText}</PageHero>
    <section className="section visit-section"><div className="wrap visit-grid"><div className="visit-info reveal reveal-left"><div className="kicker">Plan your visit</div><h2>ONIX Prague</h2><div className="info-row"><span>Location</span><div>{c.address}</div></div><div className="info-row"><span>Dinner</span><div>Monday–Sunday · 18:00–23:30<br/>Last tasting menu seating · 21:00</div></div><div className="info-row"><span>Bar</span><div>18:00–00:30 · walk-ins when seats remain</div></div><div className="info-row"><span>Music</span><div>Live performance every evening · programme varies by day</div></div><div className="info-row"><span>Contact</span><div><a href={`mailto:${c.email}`}>{c.email}</a><br/><a href={`tel:${c.phone.replace(/\s/g,'')}`}>{c.phone}</a></div></div><div className="visit-actions"><Link className="btn dark" to="/reservations">Reserve a table</Link><a className="btn" href={`https://www.openstreetmap.org/?mlat=${c.mapLat}&mlon=${c.mapLng}#map=17/${c.mapLat}/${c.mapLng}`} target="_blank" rel="noreferrer">Directions</a></div></div><div className="map-frame reveal reveal-right"><iframe title="ONIX location in Prague" loading="lazy" src={`https://www.openstreetmap.org/export/embed.html?bbox=14.3987%2C50.0828%2C14.4170%2C50.0930&layer=mapnik&marker=${c.mapLat}%2C${c.mapLng}`}/><div className="map-badge"><strong>ONIX</strong><span>Malá Strana · Prague 1</span></div></div></div></section>

    <section className="neighbourhood"><div className="wrap"><div className="section-head reveal"><div><div className="kicker">The neighbourhood</div><h2 className="display">{c.pages.visit.neighbourhoodTitle}</h2></div><p className="copy">{c.pages.visit.neighbourhoodText}</p></div><div className="prague-gallery"><figure className="reveal reveal-left"><img src="https://commons.wikimedia.org/wiki/Special:Redirect/file/Charles_Bridge_at_sunset.jpg?width=1400" alt="Charles Bridge in Prague at sunset"/><figcaption>Charles Bridge · evening walk</figcaption></figure><figure className="reveal"><img src="https://commons.wikimedia.org/wiki/Special:Redirect/file/Prague_Castle_and_Charles_Bridge_at_night.jpg?width=1400" alt="Prague Castle and Charles Bridge at night"/><figcaption>Castle skyline · after dark</figcaption></figure><figure className="reveal reveal-right"><img src="https://commons.wikimedia.org/wiki/Special:Redirect/file/Prague_Castle_at_Night_viewed_from_Charles_Bridge.jpg?width=1400" alt="Prague Castle at night viewed from Charles Bridge"/><figcaption>Vltava · Prague at night</figcaption></figure></div><p className="photo-credit">Prague photography shown from Wikimedia Commons sources.</p></div></section>

    <PrivateDiningExperience />

    <section className="section paper"><div className="wrap"><div className="section-head reveal"><div><div className="kicker">Good to know</div><h2 className="display">Before you arrive</h2></div><p className="copy">A few details to help the evening run smoothly.</p></div><div className="experience-cards"><article className="experience reveal"><div className="num">01</div><h3>Dietary requests</h3><p>Vegetarian and most allergy-sensitive menus can be prepared with advance notice.</p></article><article className="experience reveal reveal-delay-1"><div className="num">02</div><h3>Accessibility</h3><p>Main dining spaces are step-free from the courtyard entrance. Staff can arrange accessible seating in advance.</p></article><article className="experience reveal reveal-delay-2"><div className="num">03</div><h3>Late arrival</h3><p>Tables are held for 20 minutes. The tasting menu may be shortened after significant delay.</p></article></div></div></section>
  </PageShell>;
}
